### PR TITLE
Refactor MLLabelUtils to reflect obsdim changes in LearnBase.jl

### PR DESCRIPTION
**Pull request by darsnack**
This updates MLLabelUtils to reflect the changes to obsdim in https://github.com/JuliaML/LearnBase.jl/pull/44.

I have tried to restrict my refactor as much as possible to only reflect changes necessary for obsdim. I do think this repo deserves another refactor pass just for re-org/clean-up, but I think that should be part of a future PR. I gotta thank @Evizero for some absolutely fantastic tests. I do not think it would have been possible to do this refactor without introducing dispatch bugs without such a comprehensive test suite.

I also moved a bunch of interface prototypes from MLLabelUtils to LearnBase. They were marked with a comment "move to LearnBase."

I am marking this PR as a draft, because it will be merged only after we release a new LearnBase.jl. I'm preparing it right now so that we can verify that all the downstream packages (e.g. MLDataPattern and MLLabelUtils) still work correctly with the new interface.

cc @juliohm @johnnychen94

### CODE REVIEW

**Comment by johnnychen94** [comment]
So far the change on the test suits looks good to me. Given how verbose @Evizero wrote the test suit, I'm confident about the changes on `src`, too.

**Comment by racinmat** [comment]
Hi, what is the status of this? Can I help with it somehow?

**Comment by racinmat** [comment]
@darsnack  I pushed commit which makes all tests pass with `https://github.com/darsnack/LearnBase.jl#darsnack/rm-obsdim`.
Please check it out, I think it should be alllright, but maybe I have missed something.

**Comment by darsnack** [comment]
Looks good to me!

**Comment by darsnack** [comment]
Closing in favor of #46.

**Pull request closed without merging**
