### PR TITLE
julia 0.7

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@oxinabox. 
All tests are passing now. I had to flag as test_broken the the type assertions like
```julia
res = @inferred convertlabel(LabelEnc.OneOfK(Int,3), [:a,:b,:c,:b,:c,:a], [:a,:b,:c], ObsDim.Constant(1))
@test_broken typeof(res) <: typeof(x')
@test res == x'
```
since `res` is a Matrix while x' isa Adjoint{Matrix} in julia 0.7. I'm not sure what we want to do with this,
I would just remove these tests and just check with ==.

Also I get this warnings and this "skipping" that I don't know how to deal with
```julia
(v0.7) pkg> test MLLabelUtils
   Testing MLLabelUtils
 Resolving package versions...
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.active_repl
Skipping Base.active_repl_backend
┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::MLLabelUtils.LabelEnc.OneOfK{Int64,5}` with `Ref(x)` to ensure they broadcast as "scalar" elements.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The number of distinct floating point numbers (including at least one that is non-integer!) in the label vector is quite large. Are you sure you want to perform classification and not regression?
└ @ MLLabelUtils ~/.julia/dev/MLLabelUtils/src/labelencoding.jl:417
```

**Comment by Evizero** [comment]
I'd change it to `typeof(res) <: typeof(collect(x'))`. really its about the eltype I think to remember, not the array itself

**Comment by oxinabox** [comment]
Is there a reason I am being pinged?
(Not that I mind. I thought I had this repo watched)

**Comment by CarloLucibello** [comment]
> Is there a reason I am being pinged?
(Not that I mind. I thought I had this repo watched)

eh eh, right, that was hardly clear. It is because @Evizero  is not on julia 0.7 yet while you have some experience on porting to 0.7 and have been involved in this repo

**Comment by CarloLucibello** [comment]
fixed the broadcast deprecation (see https://discourse.julialang.org/t/broadcast-scalar-deprecation-warnings/11981)

The other messages I see
```julia
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.active_repl
Skipping Base.active_repl_backend
┌ Warning: The number of distinct floating point numbers (including at least one that is non-integer!) in the label vector is quite large. Are you sure you want to perform classification and not regression?
└ @ MLLabelUtils ~/.julia/dev/MLLabelUtils/src/labelencoding.jl:417
```
are also present on the master master branch on julia 0.6, so I suggest we merge this PR, tag and procede to update the rest of the ecosystem

**Comment by Evizero** [comment]
Oh I am an idiot, I forogt about this. will fix

**Comment by Evizero** [comment]
awesome. Thanks so much!

**Pull request merged**
